AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Buildkite On-Demand Agents

Transform: Buildkite-Agents-2020-03-09

Parameters:
  BuildkiteAgentTokenParameterPath:
    Type: AWS::SSM::Parameter::Name
    Description: Buildkite Agent registration token parameter path, can be a String or SecureString.
  ExecutionRolePrefix:
    Type: String
    Description: IAM Path prefix to use for ECS Execution roles.
    AllowedPattern: (\u002F[\u0021-\u007F]+\u002F)
  TaskRolePrefix:
    Type: String
    Description: IAM Path prefix to use for ECS Task roles.
    AllowedPattern: (\u002F[\u0021-\u007F]+\u002F)

Resources:
  Default:
    Type: Buildkite::ECS::TaskDefinition
    Properties:
      Image: keithduncan/buildkite-base
      BuildkiteAgentImage: keithduncan/buildkite-sidecar
      TaskFamily: buildkite